name: metaProtease
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Core Python
  - python=3.10
  - pip

  # External tools
  - bowtie2
  - samtools
  - mafft
  - fasttree 

  - pip:
     - -e .
