name: metaProtease
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Core Python
  - python=3.10
  - pip

  # External tools
  - bowtie2
  - samtools
  - mafft
  - fasttree 
  - subread
  - biopython
  - woltka
  
  # R packages
  - r-base
  - r-ggplot2
  - r-readr
  - r-dplyr
  - r-ggrepel

  # R phylogenetics and viz
  - r-ape
  - bioconductor-treeio
  - bioconductor-ggtree
  
  - pip:
     - -e .
